import turtle
import random

screen=turtle.Screen()
screen.screensize(500,500)
screen.bgcolor('lightblue')
t=turtle.Turtle()
t2=turtle.Turtle()
t2.penup()
t3=turtle.Turtle()
t2.goto(0,200)
t2.pendown()
t2.hideturtle()
t3.hideturtle()
FORCE_FACTOR = 30

#intro screen
t.penup()
t.goto(-50,150)
t.pendown()
t.pencolor("darkgreen")
t.write('All',font=('Arial',40,"bold"),align="center")
t.penup()
t.goto(-50,50)
t.pendown()
t.pencolor("darkgreen")
t.write('About',font=('Arial',40,"bold"),align="center")
t.penup()
t.goto(-50,-50)
t.pendown()
t.write('Me',font=('Arial',40,"bold"),align="center")
t.penup()
t.goto(-100,-110)
t.pendown()
t.write('-By Christian Hritz',font=('Arial',18,"bold"),align="center")
t.penup()
t.goto(100,-200)
t.pendown()
t.pencolor("red")
t.fillcolor("red")
t.begin_fill()
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.end_fill()
#space for pictures
t.penup()
t.goto(155,225)
t.pendown()
screen.addshape("friends4.gif")
t.shape("friends4.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(-100,-230)
t.pendown()
screen.addshape("endportal2.gif")
t.shape("endportal2.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(-150,-350)
t.pendown()
t.pencolor("darkgreen")
t.write('Push Enter To Continue-->',font=('Arial',15,"italic"),align="center")
round = input("Press Enter to Continue")
t.clear()

#foodscreen
screen.bgcolor('red')
t=turtle.Turtle()
t2=turtle.Turtle()
t2.penup()
t3=turtle.Turtle()
t2.goto(0,200)
t2.pendown()
t2.hideturtle()
t3.hideturtle()
FORCE_FACTOR = 30
t.penup()
t.goto(0,300)
t.pendown()
t.pencolor("yellow")
t.write('My Top 3 Foods',font=('Arial',50,"bold"),align="center")
t.penup()
t.goto(-50,150)
t.pendown()
t.pencolor("yellow")
t.write('1-Dino Nuggies',font=('Arial',20,"bold"),align="right")
t.penup()
t.goto(-70,50)
t.pendown()
t.write('2-Chick Fill A \n French Fries',font=('Arial',20,"bold"),align="right")
t.penup()
t.goto(53,-50)
t.pendown()
t.write('3-Chocolate, Chocolate \n Chip Ice Cream',font=('Arial',20,"bold"),align="right")
t.penup()
t.goto(155,-250)
t.pendown()
t.pencolor("purple")
t.fillcolor("purple")
t.begin_fill()
t.forward(90)
t.left(90)
t.forward(150)
t.left(90)
t.forward(90)
t.left(90)
t.forward(150)
t.left(90)
t.end_fill()
#open space for pictures
t.penup()
t.goto(50,170)
t.pendown()
screen.addshape("DinoNuggies.gif")
t.shape("DinoNuggies.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(50,65)
t.pendown()
screen.addshape("fries3.gif")
t.shape("fries3.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(130,-30)
t.pendown()
screen.addshape("choco.gif")
t.shape("choco.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(-150,-350)
t.pendown()
t.pencolor("yellow")
t.write('Push Enter To Continue-->',font=('Arial',15,"italic"),align="center")
round = input("Press Enter to Continue")
t.clear()

#Hobbies
screen.bgcolor('purple')
t=turtle.Turtle()
t2=turtle.Turtle()
t2.penup()
t3=turtle.Turtle()
t2.goto(0,200)
t2.pendown()
t2.hideturtle()
t3.hideturtle()
FORCE_FACTOR = 30
t.penup()
t.goto(0,300)
t.pendown()
t.pencolor("darkorange")
t.write('My Top 4 Hobbies',font=('Arial',50,"bold"),align="center")
t.penup()
t.goto(-162,150)
t.pendown()
t.pencolor("darkorange")
t.write('1-Gaming',font=('Arial',20,"bold"),align="right")
t.penup()
t.goto(-150,50)
t.pendown()
t.write('2-sleeping',font=('Arial',20,"bold"),align="right")
t.penup()
t.goto(-178,-50)
t.pendown()
t.write('3-eating',font=('Arial',20,"bold"),align="right")
t.penup()
t.goto(-50,-150)
t.pendown()
t.write('4-watching Movies',font=('Arial',20,"bold"),align="right")
#triangle
t.penup()
t.goto(155,-300)
t.pendown()
t.pencolor("blue")
t.fillcolor("blue")
t.begin_fill()
t.forward(120)
t.left(120)
t.forward(120)
t.left(120)
t.forward(120)
t.end_fill()
#open space for pictures
t.penup()
t.goto(0,160)
t.pendown()
screen.addshape("games.gif")
t.shape("games.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,80)
t.pendown()
screen.addshape("sleep.gif")
t.shape("sleep.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-50)
t.pendown()
screen.addshape("food.gif")
t.shape("food.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(65,-165)
t.pendown()
screen.addshape("movie.gif")
t.shape("movie.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(-150,-350)
t.pendown()
t.pencolor("orange")
t.write('Push Enter To Continue-->',font=('Arial',15,"italic"),align="center")
round = input("Press Enter to Continue")
t.clear()

#slide 5
screen.bgcolor('blue')
t=turtle.Turtle()
t2=turtle.Turtle()
t2.penup()
t3=turtle.Turtle()
t2.goto(0,200)
t2.pendown()
t2.hideturtle()
t3.hideturtle()
FORCE_FACTOR = 30
t.penup()
t.goto(0,300)
t.pendown()
t.pencolor("red")
t.write('My Top 5 Movies',font=('Arial',50,"bold"),align="center")
t.penup()
t.goto(-130,150)
t.pendown()
t.pencolor("red")
t.write('1-Revenge of \n The Sith',font=('Arial',20,"bold"),align="right")
t.penup()
t.goto(-160,50)
t.pendown()
t.pencolor("red")
t.write('2-Avengers \n Infinity War',font=('Arial',19,"bold"),align="right")
t.penup()
t.goto(-140,-50)
t.pendown()
t.pencolor("red")
t.write('3-Rush Hour',font=('Arial',20,"bold"),align="right")
t.penup()
t.goto(-81,-150)
t.pendown()
t.pencolor("red")
t.write('4-Minecraft Movie',font=('Arial',20,"bold"),align="right")
t.penup()
t.goto(-110,-250)
t.pendown()
t.pencolor("red")
t.write('5-Jurassic Park',font=('Arial',20,"bold"),align="right")
t.penup()
t.goto(185,-350)
t.pendown()
t.pencolor("yellow")
t.fillcolor("yellow")
t.begin_fill()
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.forward(90)
t.left(90)
t.end_fill()
#open space for pictures
t.penup()
t.goto(0,180)
t.pendown()
screen.addshape("starwars4.gif")
t.shape("starwars4.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,70)
t.pendown()
screen.addshape("marvel2.gif")
t.shape("marvel2.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-40)
t.pendown()
screen.addshape("rushhour2.gif")
t.shape("rushhour2.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-150)
t.pendown()
screen.addshape("chickenjockey2.gif")
t.shape("chickenjockey2.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,-270)
t.pendown()
screen.addshape("dino2.gif")
t.shape("dino2.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(-150,-350)
t.pendown()
t.pencolor("red")
t.write('Push Enter To Continue-->',font=('Arial',15,"italic"),align="center")
round = input("Press Enter to Continue")
t.clear()

#slide 6
screen.bgcolor('yellow')
t=turtle.Turtle()
t2=turtle.Turtle()
t2.penup()
t3=turtle.Turtle()
t2.goto(0,200)
t2.pendown()
t2.hideturtle()
t3.hideturtle()
FORCE_FACTOR = 30
t.penup()
t.goto(0,300)
t.pendown()
t.pencolor("green")
t.write('My Favorite Sport',font=('Arial',50,"bold"),align="center")
t.penup()
t.goto(0,270)
t.pendown()
t.pencolor("green")
t.write('Soccer',font=('Arial',30,"bold"),align="center")
t.penup()
t.goto(0,245)
t.pendown()
t.pencolor("green")
t.write('Because its funny to see the dramatic injuries',font=('Arial',20,"bold"),align="center")
#open space for pictures
t.penup()
t.goto(0,-150)
t.pendown()
screen.addshape("ouch1.gif")
t.shape("ouch1.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(200,-0)
t.pendown()
screen.addshape("ouch2.gif")
t.shape("ouch2.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(-200,0)
t.pendown()
screen.addshape("ouch3.gif")
t.shape("ouch3.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(0,150)
t.pendown()
screen.addshape("ouch4.gif")
t.shape("ouch4.gif")
t.stamp()
t.shape("classic")
t.penup()
t.goto(-150,-350)
t.pendown()
t.pencolor("green")
t.write('Push Enter To Continue-->',font=('Arial',15,"italic"),align="center")
round = input("Press Enter to Continue")
t.clear()

#slide 7
screen.bgcolor('black')
t=turtle.Turtle()
t2=turtle.Turtle()
t2.penup()
t3=turtle.Turtle()
t2.goto(0,200)
t2.pendown()
t2.hideturtle()
t3.hideturtle()
FORCE_FACTOR = 30
t.penup()
t.goto(0,40)
t.pendown()
t.pencolor("white")
t.write('THE',font=('Arial',50,"bold"),align="center")
t.penup()
t.goto(0,-40)
t.pendown()
t.pencolor("white")
t.write('END',font=('Arial',50,"bold"),align="center")
t.penup()
t.goto(0,-200)
t.pendown()
t.hideturtle()
t2.hideturtle()
t3.hideturtle()

turtle.done()